services:
  web:
    build: .
    restart: always
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=invecem_prod_pass_2026
      - DB_PORT=3306
      - DB_NAME=invecem
      - NEXT_PUBLIC_USE_FIREBASE=false
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=almagueralexander839@gmail.com
      - SMTP_PASS=jrsezwsqgpglrusy
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=invecem_prod_pass_2026
      - MYSQL_DATABASE=invecem
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_export.sql:/docker-entrypoint-initdb.d/db_export.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  db_data:
  caddy_data:
  caddy_config:
